import '../globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

import Nav from '@/components/nav/Nav';
import Footer from '@/components/Footer';
import AnimatedCursor from '@/components/AnimatedCursor';
import PageTransition from '@/components/page-transition/PageTransition';
import SmoothScrollbar from '@/components/SmoothScrollbar';
import { cn } from '@/utils/cn';
import { LanguagePageProps } from '@/utils/langPageProps';
import { fetchNav } from '@/lib/sanity/requests';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
} & LanguagePageProps) {
  const nav = await fetchNav();

  return (
    <html lang="en">
      <body className={cn('bg-dark text-light font-spartan relative overflow')}>
        <AnimatedCursor />
        <PageTransition />
        <SmoothScrollbar />
        <Toaster />
        <Nav nav={nav} lang={lang} />

        <div id="scrollbar" className="h-screen max-w-screen w-full">
          <div className="lg:max-w-[1620px] w-screen lg:mx-auto relative lg:pr-0">
            {children}
          </div>
          <Footer lang={lang} />
        </div>
      </body>
    </html>
  );
}
